### ISSUE TITLE
How would we incorporate custom content?

### ISSUE THREAD

**Issue by Luke1982** [coreBOS/reactadminportal#7]
What if I wanted to add custom content to the show page? We use the guessers to render the pages, but do they allow you to inject components?

**Comment by ochu-elhadji** [comment]
> What if I wanted to add custom content to the show page? We use the guessers to render the pages, but do they allow you to inject components?

Late reply, but I have to ...
I think aside prop can help in this case, it accepts the same props as edit, create and show i.e basePath, record etc
`const Aside = ({ record }) => (`
    `<div style={{ width: 200, margin: '1em' }}>`
        `<Typography variant="h6">Post details</Typography>`
        `{record && (`
            `<Typography variant="body2">`
               ` Creation date: {record.createdAt}`
           ` </Typography>`
       ` )}`
    `</div>`
`);`

`const PostEdit = props => (`
    `<Edit aside={<Aside />} {...props}>`
      ` // ...`
   ` </Edit>`
`);`
